name: Main action

on: [push]

jobs:
  checking:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -U pip poetry
          poetry config virtualenvs.create false
          poetry install --no-root

      - name: Run flake8
        run: python -m flake8 --max-line-length 88 --format=default ./src 2>&1 | tee flake8.txt

      - name: Run black
        run: python -m black ./src --check

      - name: Run bandit
        run: python -m bandit -ll -iii ./src -f json -o ./bandit.json

      - name: Run mypy
        run: python -m mypy --config-file ./pyproject.toml ./src